name: Backend CI/CD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:latest
                options: --health-cmd="curl --silent --fail http://localhost:27017/" --health-timeout=30s --health-start-period=5s --health-retries=3
                ports:
                    - 27017:27017 # Expose port 27017 for MongoDB

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: |
                  rm -rf node_modules
                  npm install
              working-directory: ./backend

            - name: Set up .env file
              run: |
                  echo "MONGODB_URI=mongodb://localhost:27017/share_trading" >> ./backend/.env

            - name: Set Permissions for Jest Binary
              run: chmod +x ./backend/node_modules/.bin/jest

            - name: Run Tests
              run: npx jest # Use npx to run Jest
              working-directory: ./backend
